# Generated by Django 2.2.6 on 2019-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('comuna', models.TextField()),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('tipo_vivienda', models.TextField()),
                ('rut', models.CharField(max_length=14)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
