# Generated by Django 2.2.6 on 2019-11-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('comuna', models.TextField()),
                ('nombre', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('tipo_vivienda', models.TextField()),
            ],
        ),
    ]
