# Generated by Django 2.2.6 on 2019-11-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datoscliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
    ]
